/**
 * Deep SEO keywords for flowers, roses, and delivery.
 * Used across layout, flowers collection, homepage, and product pages
 * so deep searches (pink roses, red roses, white flowers, flower delivery Nairobi, etc.) find the site.
 */

export const DEEP_FLOWER_ROSE_KEYWORDS = [
  // ——— Top-level flower delivery ———
  "flower delivery Nairobi",
  "flowers delivery Nairobi",
  "flower delivery Kenya",
  "fresh flower delivery Nairobi",
  "same day flower delivery Nairobi",
  "same-day flower delivery Nairobi",
  "order flowers Nairobi",
  "send flowers Nairobi",
  "buy flowers Nairobi",
  "online flower delivery Nairobi",
  "flower shop Nairobi",
  "florist Nairobi",
  "best florist Nairobi",
  "flower delivery Nairobi CBD",
  "flower delivery Westlands",
  "flower delivery Karen",
  "flower delivery Lavington",
  "flower delivery Kilimani",
  "Nairobi flower delivery",

  // ——— Roses by color (deep search) ———
  "pink roses Nairobi",
  "pink roses Kenya",
  "red roses Nairobi",
  "red roses Kenya",
  "white roses Nairobi",
  "white roses Kenya",
  "fresh pink roses Nairobi",
  "fresh red roses Nairobi",
  "fresh white roses Nairobi",
  "blooming pink roses",
  "blooming pink roses Nairobi",
  "blooming red roses",
  "blooming red roses Nairobi",
  "long stem red roses Nairobi",
  "long stem pink roses Nairobi",
  "romantic red roses Nairobi",
  "romantic pink roses Nairobi",
  "romantic white roses Nairobi",
  "red rose bouquet Nairobi",
  "pink rose bouquet Nairobi",
  "white rose bouquet Nairobi",
  "mixed roses Nairobi",
  "red and white roses Nairobi",
  "pink and white roses Nairobi",

  // ——— Flowers by color ———
  "pink flowers Nairobi",
  "red flowers Nairobi",
  "white flowers Nairobi",
  "fresh white flowers",
  "fresh white flowers Nairobi",
  "fresh pink flowers Nairobi",
  "fresh red flowers Nairobi",
  "blooming pink flowers",
  "blooming pink flowers Nairobi",
  "blooming red flowers",
  "blooming white flowers",
  "white flower bouquet Nairobi",
  "pink flower bouquet Nairobi",
  "red flower bouquet Nairobi",
  "fresh flowers Nairobi",
  "fresh flowers Kenya",
  "fresh cut flowers Nairobi",
  "luxury pink roses Nairobi",
  "luxury red roses Nairobi",
  "luxury white flowers Nairobi",

  // ——— Intent / long-tail ———
  "where to buy pink roses Nairobi",
  "where to buy red roses Nairobi",
  "where to buy white flowers Nairobi",
  "buy fresh white flowers Nairobi",
  "order pink roses online Nairobi",
  "order red roses online Nairobi",
  "same day pink roses delivery Nairobi",
  "same day red roses delivery Nairobi",
  "same day white flowers Nairobi",
  "delivery fresh flowers Nairobi",
  "fresh flower bouquet Nairobi",
  "blooming roses delivery Nairobi",
  "best pink roses Nairobi",
  "best red roses Nairobi",
  "best white flowers Nairobi",
  "affordable roses Nairobi",
  "cheap flower delivery Nairobi",
  "premium roses Nairobi",
  "hand-tied roses Nairobi",
  "rose bouquet delivery Nairobi",
  "flower bouquet Nairobi",
  "roses Nairobi",
  "bouquet delivery Nairobi",
  "money bouquet Nairobi",
  "money bouquet Kenya",
  "romantic flowers Nairobi",
  "birthday flowers Nairobi",
  "anniversary flowers Nairobi",
  "get well flowers Nairobi",
  "sympathy flowers Nairobi",
  "wedding flowers Nairobi",
  "congratulations flowers Nairobi",
];

/** Site-wide keywords for diverse Nairobi flowers, gifts and delivery (no seasonal limit) */
export const SITE_WIDE_KEYWORDS = [
  ...DEEP_FLOWER_ROSE_KEYWORDS,
  "flowers Nairobi",
  "red roses Nairobi",
  "pink roses Nairobi",
  "white roses Nairobi",
  "flower bouquets Nairobi",
  "gift hampers Nairobi",
  "teddy bears Nairobi",
  "chocolates Nairobi",
  "wines Nairobi",
  "same day delivery Nairobi",
  "Nairobi gift delivery",
];
